### ISSUE TITLE
Does it support MSI packages?

### ISSUE THREAD

**Issue by m-daniloff** [StefanKert/azuredevops-codesigning-task#6]
I was looking for a way to sign MSI package in DevOps, wondering if your tool supports that.

**Comment by StefanKert** [comment]
Hi @m-daniloff ,

as soon as I have time to review #9 this should support signing MSI packages.

I try to bring the release out until the end of the week :)

**Comment by m-daniloff** [comment]
Thanks Stefan. I managed to sign MSI package by adding Powershell script to my pipeline.

**Comment by qmatteoq** [comment]
Just to clarify, MSI and MSIX are two different things. My pull request is specific to support MSIX packages, which is the successor of the AppX format. It's the new packaging format introduced with Windows 10 1809, which aims to replace in the future all the existing installer technologies, like ClickOnce, MSI, etc. You can find more info at http://aka.ms/msix

**Comment by StefanKert** [comment]
Thanks for the clarification @qmatteoq. I have not tried if MSI is also supported with the new version because I had no testproject, but maybe the new signtool also supports this scenario?

Since I just released version 2.0.0 could you maybe check if this works now and let me know? If it doesn´t work I´d greatly appreciate it if you could prepare a small example of an MSI package that should be signed.. Thanks in advance :)

**Comment by StefanKert** [comment]
I added a test for this. .MSI signing should work :). If not please reopen the issue.
